### ISSUE TITLE
No Mobile support

### ISSUE THREAD

**Issue by coolshark** [littlstar/axis#68] opened 2016-03-30 09:36 UTC
when i switch option webgl: false  errors appears 

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create hls.min.js:3:30289
"Axis@v1.20.6
	Report bugs to https://github.com/littlstar/axis/issues (axis@littlstar.com)
	Copyright 2016 Littlstar (littlstar.com)" axis.js:174:1
THREE.CanvasRenderer 74 axis.js:45803:5
THREE.Box2: .empty() has been renamed to .isEmpty(). axis.js:34687:4
THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34708:4
THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34693:4
window.controllers è deprecato. Non utilizzarlo per rilevare l’User Agent del browser. nsHeaderInfo.js:412:8
THREE.Box2: .empty() has been renamed to .isEmpty(). axis.js:34687:4
THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34708:4
THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34693:4
THREE.Box2: .empty() has been renamed to .isEmpty(). axis.js:34687:4
THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34708:4
THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34693:4
THREE.Box2: .empty() has been renamed to .isEmpty(). axis.js:34687:4
THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34708:4
THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34693:4
THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34708:4
THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox(). axis.js:34693:4
THREE.Box2: .empty() has been renamed to .isEmpty(). axis.js:34687:4
ecc.c..

**Comment by jwerle** [comment] 2016-03-30 10:57
Looks like canvas renderer needs to be  updated. I'll get around to it
later today

**Comment by coolshark** [comment] 2016-04-13 08:46
news for this?

**Comment by jwerle** [comment] 2016-04-13 12:36
@coolshark we're working on a fix. Videos still are not working, but we've fixed photos. Look out for the next release

**Comment by coolshark** [comment] 2016-07-21 12:23
hi to all .... this bug was fixed??

**Comment by jwerle** [comment] 2016-09-20 22:41
@coolshark We're addressing this in **version 2.0**. See #102

**Comment by jwerle** [comment] 2016-09-20 22:48
duplicate of #64

**Closed by jwerle** 2016-09-20 22:48 UTC
Labels: 2.x.x, enhancement
